### PR TITLE
Tkyt to collections

### PR DESCRIPTION
**Pull request by lennyAiko**
I have changed the .json names and also added an upcoming field in all the upcoming .json files. Also made it optional in the schema - config.js.
Used filtering also when getting collections.
Anticipating the next feedback ;-)

### CODE REVIEW

**Comment by DominusKelvin** [comment]
Hey @lennyAiko I'm a bit confused as to which PR to review. Is one redundant?

**Comment by lennyAiko** [comment]
Apologies @DominusKelvin. I have closed the previous. You can review this current PR

**Comment by DominusKelvin** [comment]
Pull requests merged @lennyAiko

**Comment by lennyAiko** [comment]
Awesome! Duly noted. Looking forward to the next issue

**Pull request merged**
